-- =============================================================================
-- Enterprise Business Analytics & Decision Intelligence Platform
-- OLTP Schema DDL (PostgreSQL-compatible)
-- =============================================================================
-- Purpose : Operational source-of-truth tables for the retail simulation
-- Notes   : Star-schema facts/dims are built later via ETL; this file is OLTP only
-- =============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS oltp;
SET search_path TO oltp, public;

-- -----------------------------------------------------------------------------
-- Reference / master data
-- -----------------------------------------------------------------------------

CREATE TABLE regions (
    region_id       INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code     VARCHAR(10)     NOT NULL,
    region_name     VARCHAR(100)    NOT NULL,
    country_code    CHAR(2)         NOT NULL DEFAULT 'US',
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_regions_code UNIQUE (region_code),
    CONSTRAINT uq_regions_name UNIQUE (region_name),
    CONSTRAINT ck_regions_country CHECK (country_code ~ '^[A-Z]{2}$')
);

CREATE TABLE channels (
    channel_id      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_code    VARCHAR(20)     NOT NULL,
    channel_name    VARCHAR(50)     NOT NULL,
    channel_group   VARCHAR(30)     NOT NULL,  -- Physical / Digital
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_channels_code UNIQUE (channel_code),
    CONSTRAINT ck_channels_group CHECK (channel_group IN ('Physical', 'Digital'))
);

CREATE TABLE payment_methods (
    payment_method_id   INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_code         VARCHAR(20)     NOT NULL,
    method_name         VARCHAR(50)     NOT NULL,
    method_group        VARCHAR(30)     NOT NULL,  -- Card / Cash / Wallet / Other
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_payment_methods_code UNIQUE (method_code)
);

CREATE TABLE distribution_centers (
    dc_id           INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dc_code         VARCHAR(20)     NOT NULL,
    dc_name         VARCHAR(150)    NOT NULL,
    region_id       INTEGER         NOT NULL,
    city            VARCHAR(100)    NOT NULL,
    state_code      CHAR(2)         NOT NULL,
    postal_code     VARCHAR(15)     NOT NULL,
    capacity_units  INTEGER         NOT NULL DEFAULT 1000000,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dc_code UNIQUE (dc_code),
    CONSTRAINT ck_dc_capacity CHECK (capacity_units > 0),
    CONSTRAINT fk_dc_region
        FOREIGN KEY (region_id) REFERENCES regions (region_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE stores (
    store_id            INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code          VARCHAR(20)     NOT NULL,
    store_name          VARCHAR(150)    NOT NULL,
    region_id           INTEGER         NOT NULL,
    store_format        VARCHAR(30)     NOT NULL,
    address_line1       VARCHAR(200)    NOT NULL,
    city                VARCHAR(100)    NOT NULL,
    state_code          CHAR(2)         NOT NULL,
    postal_code         VARCHAR(15)     NOT NULL,
    latitude            DECIMAL(9, 6),
    longitude           DECIMAL(9, 6),
    selling_sq_ft       INTEGER,
    open_date           DATE            NOT NULL,
    close_date          DATE,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_stores_code UNIQUE (store_code),
    CONSTRAINT ck_stores_format CHECK (store_format IN ('Flagship', 'Standard', 'Outlet')),
    CONSTRAINT ck_stores_sqft CHECK (selling_sq_ft IS NULL OR selling_sq_ft > 0),
    CONSTRAINT ck_stores_lat CHECK (latitude IS NULL OR (latitude BETWEEN -90 AND 90)),
    CONSTRAINT ck_stores_lon CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180)),
    CONSTRAINT ck_stores_dates CHECK (close_date IS NULL OR close_date >= open_date),
    CONSTRAINT ck_stores_active_close CHECK (is_active = FALSE OR close_date IS NULL),
    CONSTRAINT fk_stores_region
        FOREIGN KEY (region_id) REFERENCES regions (region_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE calendar_date (
    date_id         INTEGER         PRIMARY KEY,          -- YYYYMMDD smart key
    full_date       DATE            NOT NULL,
    day_of_week     SMALLINT        NOT NULL,             -- 1=Mon .. 7=Sun
    day_name        VARCHAR(10)     NOT NULL,
    week_of_year    SMALLINT        NOT NULL,
    month_number    SMALLINT        NOT NULL,
    month_name      VARCHAR(15)     NOT NULL,
    quarter_number  SMALLINT        NOT NULL,
    year_number     INTEGER         NOT NULL,
    fiscal_year     INTEGER         NOT NULL,
    fiscal_quarter  SMALLINT        NOT NULL,
    is_weekend      BOOLEAN         NOT NULL DEFAULT FALSE,
    is_holiday      BOOLEAN         NOT NULL DEFAULT FALSE,
    holiday_name    VARCHAR(100),
    season_name     VARCHAR(30),
    CONSTRAINT uq_calendar_full_date UNIQUE (full_date),
    CONSTRAINT ck_calendar_dow CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT ck_calendar_week CHECK (week_of_year BETWEEN 1 AND 53),
    CONSTRAINT ck_calendar_month CHECK (month_number BETWEEN 1 AND 12),
    CONSTRAINT ck_calendar_quarter CHECK (quarter_number BETWEEN 1 AND 4),
    CONSTRAINT ck_calendar_fiscal_q CHECK (fiscal_quarter BETWEEN 1 AND 4),
    CONSTRAINT ck_calendar_holiday CHECK (
        (is_holiday = FALSE AND holiday_name IS NULL)
        OR (is_holiday = TRUE AND holiday_name IS NOT NULL)
    )
);

CREATE TABLE product_categories (
    category_id         INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code       VARCHAR(30)     NOT NULL,
    category_name       VARCHAR(150)    NOT NULL,
    parent_category_id  INTEGER,
    category_level      SMALLINT        NOT NULL,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_product_categories_code UNIQUE (category_code),
    CONSTRAINT ck_product_categories_level CHECK (category_level BETWEEN 1 AND 3),
    CONSTRAINT fk_product_categories_parent
        FOREIGN KEY (parent_category_id) REFERENCES product_categories (category_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE suppliers (
    supplier_id         INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code       VARCHAR(30)     NOT NULL,
    supplier_name       VARCHAR(200)    NOT NULL,
    supplier_tier       VARCHAR(20)     NOT NULL,
    country_code        CHAR(2)         NOT NULL DEFAULT 'US',
    payment_terms_days  INTEGER,
    lead_time_days_avg  INTEGER         NOT NULL DEFAULT 14,
    reliability_score   DECIMAL(5, 4)   NOT NULL DEFAULT 0.9000,  -- fill/on-time propensity
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_suppliers_code UNIQUE (supplier_code),
    CONSTRAINT ck_suppliers_tier CHECK (supplier_tier IN ('Strategic', 'Preferred', 'Standard')),
    CONSTRAINT ck_suppliers_terms CHECK (payment_terms_days IS NULL OR payment_terms_days > 0),
    CONSTRAINT ck_suppliers_lead CHECK (lead_time_days_avg BETWEEN 1 AND 120),
    CONSTRAINT ck_suppliers_reliability CHECK (reliability_score BETWEEN 0 AND 1)
);

CREATE TABLE customers (
    customer_id             BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number         VARCHAR(30)     NOT NULL,
    customer_type           VARCHAR(20)     NOT NULL,
    first_name              VARCHAR(100),
    last_name               VARCHAR(100),
    email_hash              VARCHAR(64),
    phone_hash              VARCHAR(64),
    birth_year              INTEGER,
    gender_code             CHAR(1),
    registration_date       DATE            NOT NULL,
    acquisition_channel_id  INTEGER,
    preferred_store_id      INTEGER,
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_customers_number UNIQUE (customer_number),
    CONSTRAINT ck_customers_type CHECK (customer_type IN ('Loyalty', 'Guest', 'Corporate')),
    CONSTRAINT ck_customers_gender CHECK (gender_code IS NULL OR gender_code IN ('M', 'F', 'U', 'N')),
    CONSTRAINT ck_customers_birth_year CHECK (
        birth_year IS NULL OR (birth_year BETWEEN 1920 AND EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER)
    ),
    CONSTRAINT fk_customers_acq_channel
        FOREIGN KEY (acquisition_channel_id) REFERENCES channels (channel_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_customers_pref_store
        FOREIGN KEY (preferred_store_id) REFERENCES stores (store_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE loyalty_accounts (
    loyalty_account_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         BIGINT          NOT NULL,
    loyalty_number      VARCHAR(30)     NOT NULL,
    tier_code           VARCHAR(20)     NOT NULL DEFAULT 'Bronze',
    enroll_date         DATE            NOT NULL,
    points_balance      INTEGER         NOT NULL DEFAULT 0,
    status_code         VARCHAR(20)     NOT NULL DEFAULT 'Active',
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_loyalty_number UNIQUE (loyalty_number),
    CONSTRAINT uq_loyalty_customer UNIQUE (customer_id),
    CONSTRAINT ck_loyalty_tier CHECK (tier_code IN ('Bronze', 'Silver', 'Gold', 'Platinum')),
    CONSTRAINT ck_loyalty_points CHECK (points_balance >= 0),
    CONSTRAINT ck_loyalty_status CHECK (status_code IN ('Active', 'Suspended', 'Closed')),
    CONSTRAINT fk_loyalty_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE customer_addresses (
    address_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT          NOT NULL,
    address_type    VARCHAR(20)     NOT NULL DEFAULT 'Shipping',
    address_line1   VARCHAR(200)    NOT NULL,
    city            VARCHAR(100)    NOT NULL,
    state_code      CHAR(2)         NOT NULL,
    postal_code     VARCHAR(15)     NOT NULL,
    country_code    CHAR(2)         NOT NULL DEFAULT 'US',
    is_primary      BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_address_type CHECK (address_type IN ('Shipping', 'Billing', 'Both')),
    CONSTRAINT fk_address_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE products (
    product_id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                     VARCHAR(40)     NOT NULL,
    product_name            VARCHAR(200)    NOT NULL,
    brand_name              VARCHAR(100),
    category_id             INTEGER         NOT NULL,
    primary_supplier_id     INTEGER,
    unit_of_measure         VARCHAR(10)     NOT NULL DEFAULT 'EA',
    current_list_price      DECIMAL(18, 2)  NOT NULL,
    current_unit_cost       DECIMAL(18, 2)  NOT NULL,
    popularity_score        DECIMAL(12, 8)  NOT NULL DEFAULT 0.00010000, -- long-tail weight
    is_active               BOOLEAN         NOT NULL DEFAULT TRUE,
    launch_date             DATE,
    discontinue_date        DATE,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_price CHECK (current_list_price >= 0),
    CONSTRAINT ck_products_cost CHECK (current_unit_cost >= 0),
    CONSTRAINT ck_products_margin CHECK (current_unit_cost <= current_list_price * 1.05),
    CONSTRAINT ck_products_dates CHECK (
        discontinue_date IS NULL OR launch_date IS NULL OR discontinue_date >= launch_date
    ),
    CONSTRAINT ck_products_popularity CHECK (popularity_score > 0),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES product_categories (category_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_products_supplier
        FOREIGN KEY (primary_supplier_id) REFERENCES suppliers (supplier_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE product_suppliers (
    product_supplier_id INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT          NOT NULL,
    supplier_id         INTEGER         NOT NULL,
    is_primary          BOOLEAN         NOT NULL DEFAULT FALSE,
    supplier_sku        VARCHAR(40),
    unit_cost           DECIMAL(18, 2)  NOT NULL,
    effective_start     DATE            NOT NULL,
    effective_end       DATE,
    CONSTRAINT uq_product_supplier UNIQUE (product_id, supplier_id, effective_start),
    CONSTRAINT ck_ps_cost CHECK (unit_cost >= 0),
    CONSTRAINT ck_ps_dates CHECK (effective_end IS NULL OR effective_end >= effective_start),
    CONSTRAINT fk_ps_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ps_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE employees (
    employee_id         INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number     VARCHAR(30)     NOT NULL,
    store_id            INTEGER         NOT NULL,
    first_name          VARCHAR(100)    NOT NULL,
    last_name           VARCHAR(100)    NOT NULL,
    job_title           VARCHAR(100)    NOT NULL,
    hire_date           DATE            NOT NULL,
    termination_date    DATE,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employees_number UNIQUE (employee_number),
    CONSTRAINT ck_employees_dates CHECK (termination_date IS NULL OR termination_date >= hire_date),
    CONSTRAINT fk_employees_store
        FOREIGN KEY (store_id) REFERENCES stores (store_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE promotions (
    promotion_id        INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_code      VARCHAR(40)     NOT NULL,
    promotion_name      VARCHAR(200)    NOT NULL,
    promotion_type      VARCHAR(30)     NOT NULL,
    discount_percent    DECIMAL(5, 2),
    discount_amount     DECIMAL(18, 2),
    start_date          DATE            NOT NULL,
    end_date            DATE            NOT NULL,
    is_stackable        BOOLEAN         NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_promotions_code UNIQUE (promotion_code),
    CONSTRAINT ck_promotions_type CHECK (
        promotion_type IN ('PercentOff', 'AmountOff', 'BOGO', 'Bundle', 'FreeShipping')
    ),
    CONSTRAINT ck_promotions_dates CHECK (end_date >= start_date),
    CONSTRAINT ck_promotions_discount CHECK (
        (discount_percent IS NULL OR discount_percent BETWEEN 0 AND 90)
        AND (discount_amount IS NULL OR discount_amount >= 0)
    )
);

CREATE TABLE marketing_campaigns (
    campaign_id         INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code       VARCHAR(40)     NOT NULL,
    campaign_name       VARCHAR(200)    NOT NULL,
    campaign_type       VARCHAR(40)     NOT NULL,
    channel_id          INTEGER,
    start_date          DATE            NOT NULL,
    end_date            DATE            NOT NULL,
    budget_amount       DECIMAL(18, 2),
    actual_spend        DECIMAL(18, 2),
    objective_code      VARCHAR(40),
    lift_factor         DECIMAL(6, 4)   NOT NULL DEFAULT 1.0500, -- relative order propensity
    status_code         VARCHAR(20)     NOT NULL DEFAULT 'Planned',
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_campaigns_code UNIQUE (campaign_code),
    CONSTRAINT ck_campaigns_type CHECK (
        campaign_type IN ('Email', 'SMS', 'Social', 'Display', 'InStore', 'Promo')
    ),
    CONSTRAINT ck_campaigns_dates CHECK (end_date >= start_date),
    CONSTRAINT ck_campaigns_budget CHECK (budget_amount IS NULL OR budget_amount >= 0),
    CONSTRAINT ck_campaigns_spend CHECK (actual_spend IS NULL OR actual_spend >= 0),
    CONSTRAINT ck_campaigns_status CHECK (
        status_code IN ('Planned', 'Active', 'Closed', 'Cancelled')
    ),
    CONSTRAINT ck_campaigns_lift CHECK (lift_factor BETWEEN 0.5 AND 3.0),
    CONSTRAINT fk_campaigns_channel
        FOREIGN KEY (channel_id) REFERENCES channels (channel_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- -----------------------------------------------------------------------------
-- Commercial transactions
-- -----------------------------------------------------------------------------

CREATE TABLE orders (
    order_id            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number        VARCHAR(40)     NOT NULL,
    customer_id         BIGINT          NOT NULL,
    store_id            INTEGER,
    channel_id          INTEGER         NOT NULL,
    order_date          DATE            NOT NULL,
    order_timestamp     TIMESTAMP       NOT NULL,
    order_status        VARCHAR(30)     NOT NULL DEFAULT 'Completed',
    currency_code       CHAR(3)         NOT NULL DEFAULT 'USD',
    gross_amount        DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    discount_amount     DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    tax_amount          DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    shipping_amount     DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    net_amount          DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    total_amount        DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    employee_id         INTEGER,
    campaign_id         INTEGER,          -- attributable campaign (nullable)
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_number UNIQUE (order_number),
    CONSTRAINT ck_orders_currency CHECK (currency_code = 'USD'),
    CONSTRAINT ck_orders_status CHECK (
        order_status IN ('Pending', 'Completed', 'Cancelled', 'Returned', 'PartiallyReturned')
    ),
    CONSTRAINT ck_orders_amounts_nonneg CHECK (
        gross_amount >= 0
        AND discount_amount >= 0
        AND tax_amount >= 0
        AND shipping_amount >= 0
        AND net_amount >= 0
        AND total_amount >= 0
    ),
    CONSTRAINT ck_orders_discount_le_gross CHECK (discount_amount <= gross_amount),
    CONSTRAINT ck_orders_ts_date CHECK (order_timestamp::DATE = order_date),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_orders_store
        FOREIGN KEY (store_id) REFERENCES stores (store_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_orders_channel
        FOREIGN KEY (channel_id) REFERENCES channels (channel_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_orders_employee
        FOREIGN KEY (employee_id) REFERENCES employees (employee_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_orders_campaign
        FOREIGN KEY (campaign_id) REFERENCES marketing_campaigns (campaign_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_orders_calendar
        FOREIGN KEY (order_date) REFERENCES calendar_date (full_date)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE order_items (
    order_item_id       BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT          NOT NULL,
    line_number         INTEGER         NOT NULL,
    product_id          BIGINT          NOT NULL,
    quantity            INTEGER         NOT NULL,
    unit_price          DECIMAL(18, 2)  NOT NULL,
    unit_cost           DECIMAL(18, 2)  NOT NULL,
    discount_amount     DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    line_gross_amount   DECIMAL(18, 2)  NOT NULL,
    line_net_amount     DECIMAL(18, 2)  NOT NULL,
    line_cogs_amount    DECIMAL(18, 2)  NOT NULL,
    promotion_id        INTEGER,
    is_gift             BOOLEAN         NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_order_items_line UNIQUE (order_id, line_number),
    CONSTRAINT ck_order_items_line_no CHECK (line_number >= 1),
    CONSTRAINT ck_order_items_qty CHECK (quantity > 0),
    CONSTRAINT ck_order_items_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_cost CHECK (unit_cost >= 0),
    CONSTRAINT ck_order_items_discount CHECK (discount_amount >= 0),
    CONSTRAINT ck_order_items_net CHECK (
        line_net_amount >= 0 AND line_net_amount <= line_gross_amount
    ),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_order_items_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotions (promotion_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE order_item_promotions (
    order_item_promotion_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id           BIGINT      NOT NULL,
    promotion_id            INTEGER     NOT NULL,
    discount_allocated      DECIMAL(18, 2) NOT NULL DEFAULT 0,
    CONSTRAINT uq_order_item_promo UNIQUE (order_item_id, promotion_id),
    CONSTRAINT ck_oip_discount CHECK (discount_allocated >= 0),
    CONSTRAINT fk_oip_item
        FOREIGN KEY (order_item_id) REFERENCES order_items (order_item_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_oip_promo
        FOREIGN KEY (promotion_id) REFERENCES promotions (promotion_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE payments (
    payment_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT          NOT NULL,
    payment_method_id   INTEGER         NOT NULL,
    payment_timestamp   TIMESTAMP       NOT NULL,
    payment_amount      DECIMAL(18, 2)  NOT NULL,
    authorization_code  VARCHAR(50),
    payment_status      VARCHAR(20)     NOT NULL DEFAULT 'Captured',
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_payments_amount CHECK (payment_amount > 0),
    CONSTRAINT ck_payments_status CHECK (
        payment_status IN ('Authorized', 'Captured', 'Voided', 'Refunded', 'Failed')
    ),
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_payments_method
        FOREIGN KEY (payment_method_id) REFERENCES payment_methods (payment_method_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE shipments (
    shipment_id         BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT          NOT NULL,
    dc_id               INTEGER,
    store_id            INTEGER,
    carrier_name        VARCHAR(100),
    tracking_number     VARCHAR(80),
    shipment_status     VARCHAR(30)     NOT NULL DEFAULT 'Shipped',
    ship_date           DATE,
    delivery_date       DATE,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_shipments_status CHECK (
        shipment_status IN ('Pending', 'Shipped', 'InTransit', 'Delivered', 'Cancelled')
    ),
    CONSTRAINT ck_shipments_dates CHECK (
        delivery_date IS NULL OR ship_date IS NULL OR delivery_date >= ship_date
    ),
    CONSTRAINT ck_shipments_origin CHECK (
        (dc_id IS NOT NULL AND store_id IS NULL)
        OR (dc_id IS NULL AND store_id IS NOT NULL)
        OR (dc_id IS NULL AND store_id IS NULL AND shipment_status IN ('Pending', 'Cancelled'))
    ),
    CONSTRAINT fk_shipments_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_shipments_dc
        FOREIGN KEY (dc_id) REFERENCES distribution_centers (dc_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_shipments_store
        FOREIGN KEY (store_id) REFERENCES stores (store_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE shipment_items (
    shipment_item_id    BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id         BIGINT          NOT NULL,
    order_item_id       BIGINT          NOT NULL,
    product_id          BIGINT          NOT NULL,
    quantity_shipped    INTEGER         NOT NULL,
    CONSTRAINT ck_shipment_items_qty CHECK (quantity_shipped > 0),
    CONSTRAINT fk_shipment_items_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipments (shipment_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_shipment_items_order_item
        FOREIGN KEY (order_item_id) REFERENCES order_items (order_item_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_shipment_items_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE returns (
    return_id           BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT          NOT NULL,
    customer_id         BIGINT          NOT NULL,
    return_date         DATE            NOT NULL,
    return_status       VARCHAR(30)     NOT NULL DEFAULT 'Completed',
    refund_amount       DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_returns_status CHECK (
        return_status IN ('Requested', 'Approved', 'Completed', 'Rejected')
    ),
    CONSTRAINT ck_returns_refund CHECK (refund_amount >= 0),
    CONSTRAINT fk_returns_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_returns_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_returns_calendar
        FOREIGN KEY (return_date) REFERENCES calendar_date (full_date)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE return_items (
    return_item_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id           BIGINT          NOT NULL,
    order_item_id       BIGINT          NOT NULL,
    product_id          BIGINT          NOT NULL,
    quantity_returned   INTEGER         NOT NULL,
    unit_refund_amount  DECIMAL(18, 2)  NOT NULL,
    restock_flag        BOOLEAN         NOT NULL DEFAULT TRUE,
    return_reason_code  VARCHAR(30),
    CONSTRAINT ck_return_items_qty CHECK (quantity_returned > 0),
    CONSTRAINT ck_return_items_refund CHECK (unit_refund_amount >= 0),
    CONSTRAINT ck_return_items_reason CHECK (
        return_reason_code IS NULL
        OR return_reason_code IN ('SIZE', 'DEFECT', 'CHANGED_MIND', 'LATE', 'WRONG_ITEM', 'OTHER')
    ),
    CONSTRAINT fk_return_items_return
        FOREIGN KEY (return_id) REFERENCES returns (return_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_return_items_order_item
        FOREIGN KEY (order_item_id) REFERENCES order_items (order_item_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_return_items_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- -----------------------------------------------------------------------------
-- Supply chain
-- -----------------------------------------------------------------------------

CREATE TABLE inventory (
    inventory_id        BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT          NOT NULL,
    location_type       VARCHAR(10)     NOT NULL,
    store_id            INTEGER,
    dc_id               INTEGER,
    quantity_on_hand    INTEGER         NOT NULL DEFAULT 0,
    quantity_reserved   INTEGER         NOT NULL DEFAULT 0,
    quantity_available  INTEGER         NOT NULL DEFAULT 0,
    reorder_point       INTEGER,
    max_stock           INTEGER,
    as_of_timestamp     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_inventory_location_type CHECK (location_type IN ('STORE', 'DC')),
    CONSTRAINT ck_inventory_qty_on_hand CHECK (quantity_on_hand >= 0),
    CONSTRAINT ck_inventory_qty_reserved CHECK (quantity_reserved >= 0),
    CONSTRAINT ck_inventory_qty_available CHECK (quantity_available >= 0),
    CONSTRAINT ck_inventory_reserved_le_onhand CHECK (quantity_reserved <= quantity_on_hand),
    CONSTRAINT ck_inventory_available_calc CHECK (
        quantity_available = quantity_on_hand - quantity_reserved
    ),
    CONSTRAINT ck_inventory_location_xor CHECK (
        (location_type = 'STORE' AND store_id IS NOT NULL AND dc_id IS NULL)
        OR (location_type = 'DC' AND dc_id IS NOT NULL AND store_id IS NULL)
    ),
    CONSTRAINT ck_inventory_reorder CHECK (
        reorder_point IS NULL OR reorder_point >= 0
    ),
    CONSTRAINT ck_inventory_max CHECK (
        max_stock IS NULL OR reorder_point IS NULL OR max_stock >= reorder_point
    ),
    CONSTRAINT uq_inventory_product_location UNIQUE (product_id, location_type, store_id, dc_id),
    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_store
        FOREIGN KEY (store_id) REFERENCES stores (store_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_dc
        FOREIGN KEY (dc_id) REFERENCES distribution_centers (dc_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE inventory_transactions (
    inventory_txn_id    BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT          NOT NULL,
    location_type       VARCHAR(10)     NOT NULL,
    store_id            INTEGER,
    dc_id               INTEGER,
    txn_type            VARCHAR(30)     NOT NULL,
    txn_date            DATE            NOT NULL,
    quantity_delta      INTEGER         NOT NULL,
    unit_cost           DECIMAL(18, 2),
    reference_id        VARCHAR(50),
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_inv_txn_location_type CHECK (location_type IN ('STORE', 'DC')),
    CONSTRAINT ck_inv_txn_type CHECK (
        txn_type IN ('RECEIPT', 'SALE', 'RETURN_RESTOCK', 'ADJUSTMENT', 'TRANSFER_IN', 'TRANSFER_OUT', 'SHRINK')
    ),
    CONSTRAINT ck_inv_txn_delta CHECK (quantity_delta <> 0),
    CONSTRAINT ck_inv_txn_location_xor CHECK (
        (location_type = 'STORE' AND store_id IS NOT NULL AND dc_id IS NULL)
        OR (location_type = 'DC' AND dc_id IS NOT NULL AND store_id IS NULL)
    ),
    CONSTRAINT fk_inv_txn_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inv_txn_store
        FOREIGN KEY (store_id) REFERENCES stores (store_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inv_txn_dc
        FOREIGN KEY (dc_id) REFERENCES distribution_centers (dc_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inv_txn_calendar
        FOREIGN KEY (txn_date) REFERENCES calendar_date (full_date)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE inventory_snapshots (
    snapshot_id         BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date       DATE            NOT NULL,
    product_id          BIGINT          NOT NULL,
    location_type       VARCHAR(10)     NOT NULL,
    store_id            INTEGER,
    dc_id               INTEGER,
    quantity_on_hand    INTEGER         NOT NULL,
    quantity_reserved   INTEGER         NOT NULL DEFAULT 0,
    quantity_available  INTEGER         NOT NULL,
    inventory_value_cost DECIMAL(18, 2) NOT NULL DEFAULT 0,
    CONSTRAINT ck_snap_location_type CHECK (location_type IN ('STORE', 'DC')),
    CONSTRAINT ck_snap_qty CHECK (
        quantity_on_hand >= 0
        AND quantity_reserved >= 0
        AND quantity_available >= 0
        AND quantity_reserved <= quantity_on_hand
    ),
    CONSTRAINT ck_snap_location_xor CHECK (
        (location_type = 'STORE' AND store_id IS NOT NULL AND dc_id IS NULL)
        OR (location_type = 'DC' AND dc_id IS NOT NULL AND store_id IS NULL)
    ),
    CONSTRAINT uq_inventory_snapshot UNIQUE (snapshot_date, product_id, location_type, store_id, dc_id),
    CONSTRAINT fk_snap_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_snap_store
        FOREIGN KEY (store_id) REFERENCES stores (store_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_snap_dc
        FOREIGN KEY (dc_id) REFERENCES distribution_centers (dc_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_snap_calendar
        FOREIGN KEY (snapshot_date) REFERENCES calendar_date (full_date)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE purchase_orders (
    purchase_order_id       BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number               VARCHAR(40)     NOT NULL,
    supplier_id             INTEGER         NOT NULL,
    dc_id                   INTEGER         NOT NULL,
    order_date              DATE            NOT NULL,
    expected_receipt_date   DATE,
    po_status               VARCHAR(30)     NOT NULL DEFAULT 'Open',
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_po_number UNIQUE (po_number),
    CONSTRAINT ck_po_status CHECK (po_status IN ('Open', 'Partial', 'Closed', 'Cancelled')),
    CONSTRAINT ck_po_dates CHECK (
        expected_receipt_date IS NULL OR expected_receipt_date >= order_date
    ),
    CONSTRAINT fk_po_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_po_dc
        FOREIGN KEY (dc_id) REFERENCES distribution_centers (dc_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_po_calendar
        FOREIGN KEY (order_date) REFERENCES calendar_date (full_date)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE purchase_order_items (
    po_item_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id   BIGINT          NOT NULL,
    line_number         INTEGER         NOT NULL,
    product_id          BIGINT          NOT NULL,
    quantity_ordered    INTEGER         NOT NULL,
    unit_cost           DECIMAL(18, 2)  NOT NULL,
    CONSTRAINT uq_po_items_line UNIQUE (purchase_order_id, line_number),
    CONSTRAINT ck_po_items_qty CHECK (quantity_ordered > 0),
    CONSTRAINT ck_po_items_cost CHECK (unit_cost >= 0),
    CONSTRAINT fk_po_items_po
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (purchase_order_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_po_items_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE goods_receipts (
    receipt_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id   BIGINT          NOT NULL,
    dc_id               INTEGER         NOT NULL,
    receipt_date        DATE            NOT NULL,
    is_on_time          BOOLEAN,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receipts_po
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (purchase_order_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_receipts_dc
        FOREIGN KEY (dc_id) REFERENCES distribution_centers (dc_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_receipts_calendar
        FOREIGN KEY (receipt_date) REFERENCES calendar_date (full_date)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE goods_receipt_items (
    receipt_item_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id          BIGINT          NOT NULL,
    po_item_id          BIGINT          NOT NULL,
    product_id          BIGINT          NOT NULL,
    quantity_received   INTEGER         NOT NULL,
    CONSTRAINT ck_receipt_items_qty CHECK (quantity_received > 0),
    CONSTRAINT fk_receipt_items_receipt
        FOREIGN KEY (receipt_id) REFERENCES goods_receipts (receipt_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_receipt_items_po_item
        FOREIGN KEY (po_item_id) REFERENCES purchase_order_items (po_item_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_receipt_items_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- -----------------------------------------------------------------------------
-- Marketing responses & labor
-- -----------------------------------------------------------------------------

CREATE TABLE campaign_responses (
    campaign_response_id    BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id             INTEGER         NOT NULL,
    customer_id             BIGINT          NOT NULL,
    response_timestamp      TIMESTAMP       NOT NULL,
    response_type           VARCHAR(30)     NOT NULL,
    order_id                BIGINT,
    attributed_revenue      DECIMAL(18, 2),
    CONSTRAINT ck_campaign_response_type CHECK (
        response_type IN ('Sent', 'Open', 'Click', 'Convert', 'Unsubscribe')
    ),
    CONSTRAINT ck_campaign_response_revenue CHECK (
        attributed_revenue IS NULL OR attributed_revenue >= 0
    ),
    CONSTRAINT fk_cr_campaign
        FOREIGN KEY (campaign_id) REFERENCES marketing_campaigns (campaign_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_cr_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_cr_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE store_labor_hours (
    labor_hours_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id            INTEGER         NOT NULL,
    employee_id         INTEGER,
    work_date           DATE            NOT NULL,
    labor_hours         DECIMAL(8, 2)   NOT NULL,
    labor_cost          DECIMAL(18, 2),
    CONSTRAINT ck_labor_hours CHECK (
        labor_hours > 0
        AND (
            (employee_id IS NULL AND labor_hours <= 500)
            OR (employee_id IS NOT NULL AND labor_hours <= 24)
        )
    ),
    CONSTRAINT ck_labor_cost CHECK (labor_cost IS NULL OR labor_cost >= 0),
    CONSTRAINT fk_labor_store
        FOREIGN KEY (store_id) REFERENCES stores (store_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_labor_employee
        FOREIGN KEY (employee_id) REFERENCES employees (employee_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_labor_calendar
        FOREIGN KEY (work_date) REFERENCES calendar_date (full_date)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE price_history (
    price_history_id    BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT          NOT NULL,
    list_price          DECIMAL(18, 2)  NOT NULL,
    effective_start     DATE            NOT NULL,
    effective_end       DATE,
    CONSTRAINT ck_price_hist_price CHECK (list_price >= 0),
    CONSTRAINT ck_price_hist_dates CHECK (
        effective_end IS NULL OR effective_end >= effective_start
    ),
    CONSTRAINT fk_price_hist_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE cost_history (
    cost_history_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT          NOT NULL,
    unit_cost           DECIMAL(18, 2)  NOT NULL,
    effective_start     DATE            NOT NULL,
    effective_end       DATE,
    CONSTRAINT ck_cost_hist_cost CHECK (unit_cost >= 0),
    CONSTRAINT ck_cost_hist_dates CHECK (
        effective_end IS NULL OR effective_end >= effective_start
    ),
    CONSTRAINT fk_cost_hist_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

COMMIT;
